apiVersion: skaffold/v2beta2
kind: Config
build:
  artifacts:
  - image: 1733116199/multi-server
    context: ./server
    sync:
      manual:
      - src: '**/*.css'
        dest: .
      - src: '**/*.html'
        dest: .
      - src: '**/*.js'
        dest: .
    docker:
      dockerfile: Dockerfile.dev
  - image: 1733116199/multi-worker
    context: ./worker
    sync:
      manual:
      - src: '**/*.js'
        dest: .
    docker:
      dockerfile: Dockerfile.dev
  local:
    push: false
deploy:
  kubectl:
    manifests:
    - k8s/server-deployment.yaml
    - k8s/worker-deployment.yaml
    - k8s/server-cluster-ip-service.yaml